#连接数据库
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mybatis?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      username: root
      password: 123456
      initialSize: 3
      minIdle: 3
      maxActive: 30
      maxWait: 15000
      validationQuery: SELECT 'x'
      #监控的配置
      stat-view-servlet:
        login-username: root
        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
        enabled: true

#mybatis的配置
mybatis:
  mapper-locations:
    - classpath:com/springboot/demo3/mapping/*Mapper.xml
  configuration:
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl

